import Head from 'next/head';
import Contacts from '../components/Contacts/contacts';
import styles from '../styles/Home.module.css';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className={`${styles.main}`}>
                <div></div>
                <div></div>
                <div></div>

                <div></div>
                <div>
                    <Contacts />
                </div>
                <div></div>
            </main>

            <footer></footer>
        </div>
    );
}
