import Head from 'next/head';
import { Fragment, useContext, useEffect, useState } from 'react';
import Contacts from '../components/Contacts/contacts';
import ContactsContext from '../context/ContactsContext';

import {prisma} from '../db';


export async function getServerSideProps() {
    const contacts = await prisma.contact.findMany();
    
    return {
        props: {
            contacts: contacts,
        },
    };
}

export default function Home(props) {
    const contactCtx = useContext(ContactsContext);
    const [contacts, setContacts] = useState(props.contacts);

    useEffect(() => {
        contactCtx.setUpContacts(contacts);
    }, [contacts]);


    return (
        <Fragment>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className='main'>
                <div></div>
                <div></div>
                <div></div>

                <Contacts />
            </main>

            <footer></footer>
        </Fragment>
    );
}
